const { _electron: electron, chromium }=require('playwright');
const fs=require('node:fs');const path=require('node:path');const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'../..');const out=path.join(root,'reports','runtime');fs.mkdirSync(out,{recursive:true});
const dataDir=process.env.GYM_SMOKE_DATA||fs.mkdtempSync(path.join(root,'build','desktop-smoke-'));
const dataFile=path.join(dataDir,'workout_data.json');
const exportFile=path.join(out,'exported-'+Date.now()+'.json');
const env={...process.env,GYMTRACKER_DATA_DIR:dataDir};delete env.ELECTRON_RUN_AS_NODE;
const results=[];let app,page;
async function launch(){app=await electron.launch({...(process.env.GYM_SMOKE_EXE?{executablePath:process.env.GYM_SMOKE_EXE,args:[]}:{args:[path.join(__dirname,'..')]}),env,timeout:60000});page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('dialog',d=>d.accept());await page.locator('#sidebar-nav-plan').waitFor();}
const read=()=>JSON.parse(fs.readFileSync(dataFile,'utf8'));
async function readJsonReady(file){for(let i=0;i<50;i++){try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch(e){if(!['EBUSY','ENOENT'].includes(e.code))throw e;await new Promise(r=>setTimeout(r,100));}}throw Error('Export file remained locked');}
async function check(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name);}catch(e){results.push({name,status:'FAIL',error:e.message});throw e;}finally{fs.writeFileSync(path.join(out,'functional.json'),JSON.stringify({dataDir,results},null,2));}}
async function persisted(predicate){await page.waitForFunction(()=>!document.body.innerText.includes('Błąd zapisu'));for(let i=0;i<80;i++){if(fs.existsSync(dataFile)&&predicate(read()))return;await new Promise(r=>setTimeout(r,100));}throw Error('Persistence assertion timed out');}
async function click(id){await page.locator('#'+id).click();}
(async()=>{
 try{
 await launch();
 await check('initial data saved to JSON',async()=>{await persisted(d=>d.weeks.length===2);});
 await check('sandbox and isolated renderer',async()=>{assert.equal(await page.evaluate(()=>typeof require),'undefined');assert.equal(await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences().contextIsolation),true);});
 const views={plan:'view-workout-plan',stats:'view-stats',muscle:'muscle-progress-view',weight:'view-body-weight',cycles:'cycle-protocol-view',exercises:'view-exercise-manager',settings:'view-settings',python:'view-python-code'};
 for(const [view,id]of Object.entries(views))await check('view '+view,async()=>{await click('sidebar-nav-'+view);await page.locator('#'+id).waitFor();await page.screenshot({path:path.join(out,'desktop-'+view+'.png')});});
 await click('sidebar-nav-plan');
 await check('add week',async()=>{await click('btn-add-week');await persisted(d=>d.weeks.length===3);});
 await check('add day',async()=>{await click('btn-add-day');await persisted(d=>d.weeks[2].days.length===4);});
 await check('add exercise + RPE + notes',async()=>{await click('btn-header-add-exercise');await page.locator('#input-exercise-name').fill('Desktop test exercise');await page.locator('#input-exercise-sets').fill('3');await page.locator('#input-exercise-reps').fill('10');await page.locator('#input-exercise-weight').fill('40');await page.locator('#select-exercise-rpe').selectOption('8');await page.locator('#input-exercise-notes').fill('Desktop regression');await click('btn-submit-exercise-modal');await persisted(d=>d.weeks[2].days[3].exercises[0]?.weight===40);});
 let ex=read().weeks[2].days[3].exercises[0].id;
 for(const [label,w]of [['+2.5',42.5],['-2.5',40],['+5.0',45]])await check('weight '+label,async()=>{await page.locator('#exercise-card-'+ex).getByRole('button',{name:label,exact:true}).click();await click('btn-save-performance-'+ex);await persisted(d=>d.weeks[2].days[3].exercises[0].weight===w&&d.weeks[2].days.every(day=>Array.isArray(day.exercises)));});
 await check('weight -5 by two existing -2.5 controls',async()=>{const b=page.locator('#exercise-card-'+ex).getByRole('button',{name:'-2.5',exact:true});await b.click();await b.click();await click('btn-save-performance-'+ex);await persisted(d=>d.weeks[2].days[3].exercises[0].weight===40);});
 await check('sets and reps',async()=>{await click('btn-plus-sets-'+ex);await click('btn-plus-reps-'+ex);await click('btn-save-performance-'+ex);await persisted(d=>d.weeks[2].days[3].exercises[0].sets===4&&d.weeks[2].days[3].exercises[0].reps===11);});
 await check('edit exercise',async()=>{const before=read().weeks[2].days[3].exercises[0];await click('btn-edit-'+ex);await page.locator('#input-exercise-name').fill('Edited desktop exercise');await click('btn-submit-exercise-modal');await persisted(d=>{const edited=d.weeks[2].days[3].exercises[0];return edited.name==='Edited desktop exercise'&&edited.history.length===before.history.length&&(before.loggedSets===undefined||edited.loggedSets?.length===before.loggedSets.length);});});
 await check('complete workout and history',async()=>{await click('btn-finish-workout-day');await persisted(d=>d.weeks[2].days[3].completed&&d.weeks[2].days[3].exercises[0].history.length>0);});
 await check('exercise history modal',async()=>{await click('btn-history-'+ex);await page.getByText('Historia Progresu: Edited desktop exercise',{exact:true}).waitFor();await page.locator('div').filter({has:page.getByText('Historia Progresu: Edited desktop exercise',{exact:true})}).filter({has:page.locator('button')}).last().getByRole('button').first().click();});
 // Close the history modal via its real close control when Escape is not implemented.
 const history=page.locator('#modal-history-window');if(await history.count())await history.getByRole('button').first().click();
 await check('duplicate week',async()=>{await click('btn-duplicate-week');await persisted(d=>d.weeks.length===4);const saved=read();assert.equal(saved.weeks[3].days[3].exercises[0].weight,42.5);assert.equal(saved.weeks[3].days[3].exercises[0].history.length,saved.weeks[2].days[3].exercises[0].history.length);});
 await check('body weight add',async()=>{await click('sidebar-nav-weight');await page.locator('#input-bw-weight').fill('81.5');await page.locator('#input-bw-notes').fill('Desktop test');await click('btn-submit-bw');await persisted(d=>d.bodyWeights.some(b=>b.notes==='Desktop test'));});
 await check('manual backup',async()=>{await click('sidebar-nav-settings');await click('btn-create-backup-now');await persisted(d=>!!d.settings.lastBackupTime);assert.ok(fs.readdirSync(path.join(dataDir,'backups')).length>0);});
 await check('invalid import preserves data',async()=>{const before=read().weeks.length;const bad=path.join(out,'invalid.json');fs.writeFileSync(bad,'{"weeks":[]}');await page.locator('input[type=file]').first().setInputFiles(bad);await page.getByText('Błąd parsowania pliku JSON.',{exact:true}).waitFor();assert.equal(read().weeks.length,before);});
 await check('export JSON via real download',async()=>{const dest=exportFile;await app.evaluate(({BrowserWindow},dest)=>{BrowserWindow.getAllWindows()[0].webContents.session.once('will-download',(_e,item)=>item.setSavePath(dest));},dest);await click('btn-export-json');const exported=await readJsonReady(dest);assert.equal(exported.weeks[2].days[3].exercises[0].id,ex);});
 await check('import exported JSON',async()=>{await page.locator('input[type=file]').first().setInputFiles(exportFile);await persisted(d=>d.weeks[2].days[3].exercises[0].id===ex);});
 await check('restart preserves changed data',async()=>{await app.close();await launch();assert.equal(read().weeks[2].days[3].exercises[0].name,'Edited desktop exercise');await page.locator('#btn-week-'+read().weeks[2].id).click();assert.equal(await page.locator('[id^=btn-day-]').count(),4);});
 await check('day notes',async()=>{await page.locator('#btn-day-'+read().weeks[2].days[3].id).click();if(!await page.locator('#day-notes-textarea').isVisible())await click('btn-toggle-day-notes');await page.locator('#day-notes-textarea').fill('Saved desktop day notes');await page.locator('#day-notes-textarea').press('Tab');await persisted(d=>d.weeks[2].days[3].notes==='Saved desktop day notes');});
 await check('native rename prompt',async()=>{const w=read().weeks[2];const promptWindow=app.waitForEvent('window');const trigger=page.locator('#btn-week-'+w.id+' [role=button]').click();const prompt=await promptWindow;await prompt.locator('input').fill('Renamed desktop week');await prompt.locator('button[type=submit]').click();await trigger;await persisted(d=>d.weeks[2].name==='Renamed desktop week');});
 await check('delete exercise',async()=>{await click('btn-delete-'+ex);await persisted(d=>d.weeks[2].days[3].exercises.length===0);});
 await check('delete day',async()=>{await page.getByRole('button',{name:'Usuń dzień',exact:true}).click();await persisted(d=>d.weeks[2].days.length===3);});
 await check('delete duplicate week',async()=>{await click('btn-week-'+read().weeks[3].id);await click('btn-delete-week');await persisted(d=>d.weeks.length===3);});
 await check('cycle entry',async()=>{await click('sidebar-nav-cycles');await page.getByPlaceholder('np. Testosteron Enanthat, HCG, Masteron...').fill('TEST DATA');await page.getByPlaceholder('250',{exact:true}).fill('1');await click('btn-save-protocol-entry');await persisted(d=>d.protocolEntries.some(p=>p.substance==='TEST DATA'&&p.dosage===1));});
 await check('delete body weight',async()=>{await click('sidebar-nav-weight');await page.locator('tr').filter({hasText:'Desktop test'}).getByRole('button',{name:'Usuń wpis'}).click();await persisted(d=>!d.bodyWeights.some(b=>b.notes==='Desktop test'));});
await check('settings change persists',async()=>{await click('sidebar-nav-settings');const input=page.locator('#view-settings input[type=text]').filter({visible:true});const fields=await input.all();for(const f of fields){if(await f.inputValue()==='Zawodnik'){await f.fill('Desktop QA');break;}}await persisted(d=>d.settings.athleteName==='Desktop QA');});
 await check('settings diagnostics and analysis reset works',async()=>{assert.equal(await page.locator('#settings-diagnostics').count(),1);const reset=page.locator('#btn-reset-analysis-settings');assert.equal(await reset.count(),1);const start=page.locator('#input-analysis-start-week');if(await start.count()){await start.fill('4');await start.blur();await reset.click();assert.equal(await start.inputValue(),'1');}});
 await check('catalog edits exercise outside selected day',async()=>{await click('sidebar-nav-exercises');const card=page.locator('#view-exercise-manager .group').filter({has:page.getByRole('heading',{name:'Wyciskanie sztangi na ławce płaskiej',exact:true})});await card.getByRole('button',{name:'Edytuj',exact:true}).click();await page.locator('#input-exercise-notes').fill('Catalog edited');await click('btn-submit-exercise-modal');await persisted(d=>d.weeks[0].days[0].exercises[0].notes==='Catalog edited');});
 await check('catalog deletes exercise outside selected day',async()=>{const name=read().weeks[0].days[0].exercises[0].name;const card=page.locator('#view-exercise-manager .group').filter({has:page.getByRole('heading',{name,exact:true})});await card.getByRole('button',{name:'Usuń ćwiczenie z planu'}).click();await persisted(d=>!d.weeks[0].days[0].exercises.some(e=>e.name===name));});
 await app.close();app=null;
 console.log(JSON.stringify({passed:results.length,dataDir}));
 }catch(e){console.error(e);process.exitCode=1;if(app)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});}
 finally{if(app)await app.close().catch(()=>{});}
})();
